#!/usr/bin/env bash

TMUX_PLUGIN_DIR="$HOME/.tmux/plugins/tpm/bin"

# Install tmux plugins
${TMUX_PLUGIN_DIR}/install_plugins

# Update tmux plugins
${TMUX_PLUGIN_DIR}/update_plugins all

# Remove plugsins no longer in the plugin list
${TMUX_PLUGIN_DIR}/clean_plugins

# Update vim-plug
if [[ -f "$HOME/.local/share/nvim/site/autoload/plug.vim" ]]; then
  nvim -E -s +PlugUpgrade +qa
  nvim -u "$HOME/.config/nvim/init.vim" +PlugUpdate +PlugClean! +qa
fi

# Link etc/wsl.conf to /etc/wsl.conf
if [[ ! -f '/etc/wsl.conf' ]]; then
  sudo cp ~/.dotfiles/etc/wsl.conf /etc/wsl.conf
fi

# Link the VsXsrv Configuration to the Correct Windows Directory
# depending on Windows username
if [[ -d '/c/Users/ncron' ]]; then
  echo "Link config xlaunch"
  ln -sf ~/.dotfiles/c/Users/user/AppData/Roaming/Microsoft/Windows/Start\ Menu/Programs/Startup/config.xlaunch /c/Users/ncron/AppData/Roaming/Microsoft/Windows/Start\ Menu/Programs/Startup/config.xlaunch
elif [[ -d '/c/Users/cronquin' ]]; then
  ln -sf ~/.dotfiles/c/Users/user/AppData/Roaming/Microsoft/Windows/Start\ Menu/Programs/Startup/config.xlaunch /c/Users/cronquin/AppData/Roaming/Microsoft/Windows/Start\ Menu/Programs/Startup/config.xlaunch
fi
